server:
  port: 8081

spring:  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect