jwt:
  secret: '[a-zA-Z0-9._]^$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
  # The above is a random string
  
server:
  port: 8081

spring:  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
